- README.md
- cli.js
- index.ts
- tests/es7-class-top-level-module.d.ts
- tests/parsing-test.ts
- tsconfig.json
This options adds the ability to create typings definition which could be used to add them to npm
packages
> feat: Adds option create write typings to top-level

- README.md
- package.json
Utilize standard-version to create changelog
> chore(build): Using standard-version

- .travis.yml
* enable travis cache
* build with node 4,5,6
> chore: updates travis configuration

- package.json
> chore(package): update typescript to version 2.0.3

- package.json
> chore(package): update babel-register to version 6.16.0

- package.json
> chore(package): update nyc to version 8.3.2

- package.json
- src/types.ts
- src/typings.ts
- tests/parsing-test.ts
- tests/references-in-proptypes.d.ts
- tests/references-in-proptypes.jsx
> feat: resolve references in oneOf propTypes

- tests/es6-class.d.ts
- tests/es6-class.jsx
> Add a test case to prove nested complex types are working

- src/types.ts
- tests/references-in-proptypes.d.ts
- tests/references-in-proptypes.jsx
> fix: handle references for shapes correctly

- package.json
- src/generator.ts
> chore(package): update tslint to version 4.4.1

- package.json
> chore(package): update @types/react to version 15.0.11

- package.json
> chore(package): update @types/react to version 15.0.12

- package.json
> chore(package): update @types/react to version 15.0.13

- tests/component-without-proptyes.d.ts
- tests/es6-class.d.ts
- tests/es7-class-separate-export.d.ts
- tests/es7-class-top-level-module.d.ts
- tests/es7-class.d.ts
- tests/import-react-component.d.ts
- tests/instance-of-proptype-names.d.ts
- tests/parsing-test.ts
- tests/references-in-proptypes.d.ts
- tests/stateless.d.ts
By normalizing output and test fixtures the tests are more robust to changes during typings creation
> test: make tests more robust

- package.json
- src/generator.ts
> chore(package): update @knisterpeter/standard-tslint to version 1.3.0

- tests/parsing-test.ts
- tsconfig.json
- wallaby.conf.js
As described here https://github.com/wallabyjs/public/issues/1050#issuecomment-283280201 we need to update dts-dom. 
RyanCavanaugh/dts-dom#17
> chore: add wallaby config

- package.json
- src/types.ts
- src/typings.ts
- tests/error-reporting-test.ts
When failing to infer types instead of print error trace, report source except
Closes #247
> feat: report error context and source excerpt

- package.json
> chore(package): update @types/react to version 15.0.14

- package.json
> chore(package): update @types/react to version 15.0.16

- package.json
> chore(package): update @types/react to version 15.0.17

- package.json
> chore(package): update @types/react to version 15.0.18

- package.json
> chore(package): update @types/react to version 15.0.21

- src/typings.ts
- tests/parsing-test.ts
- tests/unnamed-default-export.d.ts
- tests/unnamed-default-export.jsx
> fix: handle unnamed default export

- cli.js
- src/index.ts
- src/typings.ts
- tests/parsing-test.ts
- tests/preact-definition.d.ts
- tests/preact-definition.jsx
- tests/unnamed-default-export.d.ts
> feat: support output for react-like libraries

- src/typings.ts
- tests/named-export-specifiers.d.ts
- tests/named-export-specifiers.jsx
- tests/parsing-test.ts
> fix: handle named export specifiers

- package.json
> chore(package): update @types/react to version 15.0.23

- package.json
> fix(package): update babylon to version 7.0.0-beta.34

- package-lock.json
- package.json
- src/typings.ts
- tests/named-export-specifiers.d.ts
- tests/stateless-export-as-default.d.ts
- tests/stateless.d.ts
depends on https://github.com/RyanCavanaugh/dts-dom/pull/36 ✅
> fix: add react import to SFC typings

- package-lock.json
- package.json
- tests/es6-class.d.ts
- tests/es6-class.jsx
> fix: add parentheses around function in union by updating dts-dom

- package-lock.json
- package.json
- src/typings.ts
- tests/named-export-specifiers.d.ts
- tests/stateless-export-as-default.d.ts
- tests/stateless.d.ts
> fix: for SFCs use triple slash directive instead of react import

- src/index.ts
- src/typings.ts
- tests/parsing-test.ts
> feat: allow custom eol characters

- src/index.ts
- tests/babylon-plugin.d.ts
- tests/babylon-plugin.jsx
- tests/parsing-test.ts
fix: https://github.com/KnisterPeter/react-to-typescript-definitions/issues/608
> feat: allow users to set additional babylon plugins

- .travis.yml
BREAKING CHANGE: drop support for node6
> chore: drop support for node6

- src/types.ts
- tests/es6-class.d.ts
- tests/es6-class.jsx
closes https://github.com/KnisterPeter/react-to-typescript-definitions/issues/1131
> fix: handle nested string literal props
